"""Convert OGSOD-1.0 DOTA-style labels to Ultralytics YOLO OBB labels.

Input line:
    x1 y1 x2 y2 x3 y3 x4 y4 class_name difficult

Output line:
    class_id x1 y1 x2 y2 x3 y3 x4 y4
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import random
import shutil
from collections import Counter
from pathlib import Path

from PIL import Image


DEFAULT_CLASSES = {"bridge": 0, "harbor": 1, "storage_tank": 2}
IMAGE_SUFFIXES = {".bmp", ".jpeg", ".jpg", ".png", ".tif", ".tiff", ".webp"}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-root", type=Path, required=True, help="OGSOD-1.0 source root.")
    parser.add_argument("--obb-root", type=Path, required=True, help="Directory containing train/ and test/labelTxt.")
    parser.add_argument("--output", type=Path, required=True, help="Derived YOLO OBB dataset directory.")
    parser.add_argument("--val-fraction", type=float, default=0.1)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--images-mode", choices=("symlink", "copy", "none"), default="symlink")
    return parser.parse_args()


def polygon_area(points: list[tuple[float, float]]) -> float:
    return abs(
        sum(
            points[index][0] * points[(index + 1) % 4][1]
            - points[(index + 1) % 4][0] * points[index][1]
            for index in range(4)
        )
    ) / 2.0


def prepare_output(output: Path) -> None:
    marker = output / ".ogsod_derived"
    if output.exists() and any(output.iterdir()) and not marker.exists():
        raise FileExistsError(f"Output directory is not empty and is not marked as generated: {output}")
    output.mkdir(parents=True, exist_ok=True)
    marker.write_text("Generated by scripts/convert_ogsod_obb.py\n", encoding="utf-8")


def link_or_copy(source: Path, target: Path, mode: str) -> None:
    target.parent.mkdir(parents=True, exist_ok=True)
    if target.is_symlink() or target.exists():
        if target.is_dir() and not target.is_symlink():
            shutil.rmtree(target)
        else:
            target.unlink()
    if mode == "symlink":
        target.symlink_to(source.resolve(), target_is_directory=True)
    elif mode == "copy":
        shutil.copytree(source, target, dirs_exist_ok=True)
    elif mode != "none":
        raise ValueError(f"Unsupported image mode: {mode}")


def convert_split(
    split: str,
    image_dir: Path,
    label_dir: Path,
    output: Path,
    class_mapping: dict[str, int],
) -> tuple[list[str], list[dict], Counter[str], Counter[str]]:
    output_label_dir = output / "labels" / split
    output_label_dir.mkdir(parents=True, exist_ok=True)
    image_files = sorted(path for path in image_dir.rglob("*") if path.suffix.lower() in IMAGE_SUFFIXES)
    label_files = {path.stem: path for path in label_dir.rglob("*.txt")}
    image_paths: list[str] = []
    removed: list[dict] = []
    class_counts: Counter[str] = Counter()
    stats: Counter[str] = Counter()

    for image_path in image_files:
        label_path = label_files.get(image_path.stem)
        if label_path is None:
            raise FileNotFoundError(f"Missing OBB label for {image_path}")
        with Image.open(image_path) as image:
            width, height = image.size

        converted_lines = []
        for line_number, line in enumerate(label_path.read_text(encoding="utf-8").splitlines(), start=1):
            parts = line.split()
            if not parts:
                continue
            if len(parts) != 10:
                raise ValueError(f"Invalid OBB label fields in {label_path}:{line_number}: {len(parts)}")
            class_name = parts[8]
            if class_name not in class_mapping:
                raise ValueError(f"Unknown class '{class_name}' in {label_path}:{line_number}")

            raw = [float(value) for value in parts[:8]]
            clipped = False
            clipped_coords = []
            for index, value in enumerate(raw):
                limit = width if index % 2 == 0 else height
                new_value = min(max(value, 0.0), float(limit))
                clipped = clipped or new_value != value
                clipped_coords.append(new_value)
            if clipped:
                stats["clipped_boxes"] += 1
                stats["clipped_coordinates"] += sum(
                    min(max(value, 0.0), float(width if index % 2 == 0 else height)) != value
                    for index, value in enumerate(raw)
                )

            points = list(zip(clipped_coords[0::2], clipped_coords[1::2]))
            if polygon_area(points) <= 1e-8:
                removed.append(
                    {
                        "split": split,
                        "image": image_path.name,
                        "label": str(label_path),
                        "line": line_number,
                        "class_name": class_name,
                        "reason": "zero_area",
                        "raw": line,
                    }
                )
                stats["removed_zero_area"] += 1
                continue

            normalized = [
                value / (width if index % 2 == 0 else height)
                for index, value in enumerate(clipped_coords)
            ]
            class_id = class_mapping[class_name]
            converted_lines.append(
                f"{class_id} " + " ".join(f"{value:.8f}" for value in normalized)
            )
            class_counts[class_name] += 1
            stats["converted_objects"] += 1

        output_label_path = output_label_dir / f"{image_path.stem}.txt"
        output_label_path.write_text("\n".join(converted_lines) + ("\n" if converted_lines else ""), encoding="utf-8")
        image_paths.append(str((output / "images" / split / image_path.name).resolve()))

    missing_labels = set(label_files) - {path.stem for path in image_files}
    if missing_labels:
        raise FileNotFoundError(f"Found {len(missing_labels)} labels without images in {label_dir}")
    stats["images"] = len(image_files)
    return image_paths, removed, class_counts, stats


def write_list(path: Path, entries: list[str]) -> None:
    path.write_text("\n".join(entries) + "\n", encoding="utf-8")


def main() -> None:
    args = parse_args()
    if not 0.0 < args.val_fraction < 1.0:
        raise ValueError("--val-fraction must be between 0 and 1.")

    source_root = args.source_root.resolve()
    obb_root = args.obb_root.resolve()
    output = args.output.resolve()
    prepare_output(output)

    image_root = source_root / "sar" / "images"
    for split in ("train", "test"):
        link_or_copy(image_root / split, output / "images" / split, args.images_mode)

    train_images, train_removed, train_counts, train_stats = convert_split(
        "train", image_root / "train", obb_root / "train" / "labelTxt", output, DEFAULT_CLASSES
    )
    test_images, test_removed, test_counts, test_stats = convert_split(
        "test", image_root / "test", obb_root / "test" / "labelTxt", output, DEFAULT_CLASSES
    )

    rng = random.Random(args.seed)
    rng.shuffle(train_images)
    val_size = max(1, round(len(train_images) * args.val_fraction))
    val_images = sorted(train_images[:val_size])
    fit_images = sorted(train_images[val_size:])
    write_list(output / "train.txt", fit_images)
    write_list(output / "val.txt", val_images)
    write_list(output / "test.txt", sorted(test_images))

    names = [name for name, _ in sorted(DEFAULT_CLASSES.items(), key=lambda item: item[1])]
    data_yaml = [
        f"path: {output}",
        "train: train.txt",
        "val: val.txt",
        "test: test.txt",
        "names:",
        *[f"  {index}: {name}" for index, name in enumerate(names)],
        "",
    ]
    (output / "data.yaml").write_text("\n".join(data_yaml), encoding="utf-8")

    removed = train_removed + test_removed
    if removed:
        with (output / "removed_labels.csv").open("w", newline="", encoding="utf-8") as handle:
            writer = csv.DictWriter(handle, fieldnames=list(removed[0]))
            writer.writeheader()
            writer.writerows(removed)

    summary = {
        "source_root": str(source_root),
        "obb_root": str(obb_root),
        "output": str(output),
        "seed": args.seed,
        "val_fraction": args.val_fraction,
        "images_mode": args.images_mode,
        "splits": {
            "train_fit": len(fit_images),
            "val": len(val_images),
            "test": len(test_images),
        },
        "converted_objects": int(train_stats["converted_objects"] + test_stats["converted_objects"]),
        "removed_zero_area": len(removed),
        "clipped_boxes": int(train_stats["clipped_boxes"] + test_stats["clipped_boxes"]),
        "clipped_coordinates": int(train_stats["clipped_coordinates"] + test_stats["clipped_coordinates"]),
        "class_counts": {
            "train": dict(train_counts),
            "test": dict(test_counts),
        },
    }
    (output / "conversion_summary.json").write_text(
        json.dumps(summary, indent=2, ensure_ascii=True), encoding="utf-8"
    )
    print(json.dumps(summary, indent=2, ensure_ascii=True))


if __name__ == "__main__":
    main()
